import React, { useState } from 'react'
import { useRouter } from 'next/router'
import Head from 'next/head'
import { setItem } from '/components/LocalStorage'
import styles from '../../styles/Home.module.css'
import { signInWithGithub } from '../../components/FirebaseAuth'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faGithub } from "@fortawesome/free-brands-svg-icons";

const Login = () => {
  const router = useRouter();
  return(
    <div className={styles.container}>
      <Head>
        <title>KiyomiTalk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>KiyomiTalk</h1>
        <p className={styles.description}>
          Let&#39;s go
          <code className={styles.code}>Crazy Katsu!</code>
        </p>
        <div className={styles.login}>
          <a 
            style={{
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              backgroundColor: "#fff",
              padding: "5px 14px 5px 7px",
              borderRadius: "7px",
              cursor: "pointer",
              boxShadow: "0px 0px 5px #000"
            }}

            onClick={async () => {
              const user = await signInWithGithub()
              setItem('cachedUser', user)
              router.push('/rooms')
            }}
          >
            <FontAwesomeIcon 
              icon={faGithub} 
              width="30" 
              height="30" 
              style={{
                marginRight: "4px"
              }}/>
            <span>Github Login</span>
          </a>
        </div>
      </main>
    </div>
  )
}
  
export default Login;
