import React, { useState } from 'react'
import { useRouter } from 'next/router'
import Head from 'next/head'
import { setItem } from '/components/LocalStorage'
import styles from '../../styles/Home.module.css'
import { signInWithGithub } from '../../components/FirebaseAuth'

const Login = () => {
  const [nickname, setNickname] = useState('');
  const router = useRouter();
  return(
    <div className={styles.container}>
      <Head>
        <title>KiyomiTalk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>KiyomiTalk</h1>
        <p className={styles.description}>
          Let&#39;s go
          <code className={styles.code}>Crazy Katsu!</code>
        </p>
        <div className={styles.login}>
          <p className={styles.text}>닉네임</p>
          <input 
            type="text" 
            className={styles.input}
            placeholder="닉네임을 입력하세요."
            onChange={({ target }) => setNickname(target.value)}
          />
          
          <button 
            type="button" 
            className={styles.btnlogin}
            onClick={() => {
              if (!nickname) {
                alert('닉네임을 입력해라!');
                return;
              }
              setItem('nickname', nickname)
              router.push(`/rooms`);
            }}
          >
            로그인
          </button>
          <button 
            type="button" 
            className={styles.btnlogin}
            onClick={async () => {
              const user = await signInWithGithub()
              setItem('cachedUser', user)
            }}
          >
            test
          </button>
        </div>
      </main>
    </div>
  )
}
  
export default Login;
